### ISSUE TITLE
getting logo.png not found

### ISSUE THREAD

**Issue by vishunair1986** [jimgilsinn/PiConSrv#1]
Please help as iam new to this , iam getting ' Something went wrong, printing error: Couldn't open logo.png'

**Comment by jimgilsinn** [comment]
The software is still in early development, and requires certain files to be located in the run directory:
logo.png == a logo image to display on the screen, should be 250x100 pixels
conference.txt == the full database of conference attendees output from "BusyConf"
manual.txt == any manually entered conference registrations
registered.txt == automatically registered attendees via the "conqr" software

I'm still working on writing the software's basic functionality, so I haven't gotten around to making it more functional with configuration or command-line options.
